### PR TITLE
fix #66

### LINKED ISSUE #66: scanning caught an error: bufio.Scanner: token too long
Hi, 

This is eseentially the same issue as #53. My JSON payload is larger than 1MB thus crashing the program. I want to suggest using `scanner.Err() == bufio.ErrTooLong` to handle such cases.

### PR DESCRIPTION
**Pull request by KevRiver**
- [x] Write a test that reproduces the problem
- [x] Fix it. The test should now pass

### CODE REVIEW

**Comment by aybabtme** [comment]
what did you think about the suggestion in #66 to use catch `scanner.Err() == bufio.ErrTooLong`?

File: scanner_test.go [hunk 1]
```diff
@@ -46,6 +46,22 @@ func TestScannerLongLine(t *testing.T) {
...
+	ctx := context.Background()
+	payload := `{"msg":` + strings.Repeat("a", 1024*1024) + `}` // more than 1mb long json payload
+	src := strings.NewReader(payload)
+
+	opts := DefaultOptions()
+	opts.timeNow = func() time.Time {
+		return time.Date(2024, 11, 1, 15, 40, 0, 0, time.UTC)
+	}
+
+	sink := bufsink.NewSizedBufferedSink(1024*1024, nil)
```
Comment (aybabtme) [inline scanner_test.go:60]: this sized buffered sink isn't related to the scanning buffer, its simply buffering `[100]*types.LogEvent`
```suggestion
	sink := bufsink.NewSizedBufferedSink(100, nil)
```

in fact this test here should inspect the content of that buffer after parsing a message that's too long:

```
	require.Len(t, sink.Buffered, len(want))
	for i, got := range sink.Buffered {
		require.Equal(t, pjson(want[i]), pjson(got))
	}
```

i think you want to demonstrate 2 things:
- [ ] the scanner didn't die because of the excessively long input
- [ ] the scanner kept on scanning log events despite the input that was too long
right now the test doesn't demonstrate this, afaict

File: scanner_test.go [hunk 2]
```diff
@@ -46,6 +46,22 @@ func TestScannerLongLine(t *testing.T) {
 	}
 }
 
+func TestLargePayload(t *testing.T) {
+
+	ctx := context.Background()
+	payload := `{"msg":` + strings.Repeat("a", 1024*1024) + `}` // more than 1mb long json payload
```
Comment (aybabtme) [inline scanner_test.go:52]:
```suggestion
	payload := `{"msg":` + strings.Repeat("a", 2*1024*1024) + `}` // more than 1mb long json payload
```
shouldn't this be large enough to overflow the buffer?

also, probably better to use the `bufferMaxSize` constant
```suggestion
	payload := `{"msg":` + strings.Repeat("a", bufferMaxSize + 1) + `}` // more than 1mb long json payload
```

**Review by aybabtme — APPROVED** [review]
